export const types = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  GET_TIPOUSER_START: 'GET_TIPOUSER_START',
  GET_TIPOUSER_SUCCESS: 'GET_TIPOUSER_SUCCESS',
  GET_TIPOUSER_FAILED: 'GET_TIPOUSER_FAILED',

  GET_USERINFO_START: 'GET_USERINFO_START',
  GET_USERINFO_SUCCESS: 'GET_USERINFO_SUCCESS',
  GET_USERINFO_FAILED: 'GET_USERINFO_FAILED',

  GET_ALLUSERS_START: 'GET_ALLUSERS_START',
  GET_ALLUSERS_SUCCESS: 'GET_ALLUSERS_SUCCESS',
  GET_ALLUSERS_FAILED: 'GET_ALLUSERS_FAILED',

  GET_ALLUSERSREPORT_START: 'GET_ALLUSERSREPORT_START',
  GET_ALLUSERSREPORT_SUCCESS: 'GET_ALLUSERSREPORT_SUCCESS',
  GET_ALLUSERSREPORT_FAILED: 'GET_ALLUSERSREPORT_FAILED',

  UPDATE_USERINFO_START: 'UPDATE_USERINFO_START',
  UPDATE_USERINFO_SUCCESS: 'UPDATE_USERINFO_SUCCESS',
  UPDATE_USERINFO_FAILED: 'UPDATE_USERINFO_FAILED',

  UPDATE_USUARIO_START: 'UPDATE_USUARIO_START',
  UPDATE_USUARIO_SUCCESS: 'UPDATE_USUARIO_SUCCESS',
  UPDATE_USUARIO_FAILED: 'UPDATE_USUARIO_FAILED',

  UPDATE_ESTADOUSUARIO_START: 'UPDATE_ESTADOUSUARIO_START',
  UPDATE_ESTADOUSUARIO_SUCCESS: 'UPDATE_ESTADOUSUARIO_SUCCESS',
  UPDATE_ESTADOUSUARIO_FAILED: 'UPDATE_ESTADOUSUARIO_FAILED',

  UPDATE_PASSWORD_START: 'UPDATE_PASSWORD_START',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILED: 'UPDATE_PASSWORD_FAILED',

  GET_EJECUTIVO_START: 'GET_EJECUTIVO_START',
  GET_EJECUTIVO_SUCCESS: 'GET_EJECUTIVO_SUCCESS',
  GET_EJECUTIVO_FAILED: 'GET_EJECUTIVO_FAILED',

  GET_ALLEJECUTIVO_START: 'GET_ALLEJECUTIVO_START',
  GET_ALLEJECUTIVO_SUCCESS: 'GET_ALLEJECUTIVO_SUCCESS',
  GET_ALLEJECUTIVO_FAILED: 'GET_ALLEJECUTIVO_FAILED',

  POST_EJECUTIVO_START: 'POST_EJECUTIVO_START',
  POST_EJECUTIVO_SUCCESS: 'POST_EJECUTIVO_SUCCESS',
  POST_EJECUTIVO_FAILED: 'POST_EJECUTIVO_FAILED',

  UPDATE_EJECUTIVO_START: 'UPDATE_EJECUTIVO_START',
  UPDATE_EJECUTIVO_SUCCESS: 'UPDATE_EJECUTIVO_SUCCESS',
  UPDATE_EJECUTIVO_FAILED: 'UPDATE_EJECUTIVO_FAILED',

  DELETE_EJECUTIVO_START: 'DELETE_EJECUTIVO_START',
  DELETE_EJECUTIVO_SUCCESS: 'DELETE_EJECUTIVO_SUCCESS',
  DELETE_EJECUTIVO_FAILED: 'DELETE_EJECUTIVO_FAILED',

  UPDATE_ESTADOEJECUTIVO_START: 'UPDATE_ESTADOEJECUTIVO_START',
  UPDATE_ESTADOEJECUTIVO_SUCCESS: 'UPDATE_ESTADOEJECUTIVO_SUCCESS',
  UPDATE_ESTADOEJECUTIVO_FAILED: 'UPDATE_ESTADOEJECUTIVO_FAILED',

  GET_GRUPOFAMILIAR_START: 'GET_GRUPOFAMILIAR_START',
  GET_GRUPOFAMILIAR_SUCCESS: 'GET_GRUPOFAMILIAR_SUCCESS',
  GET_GRUPOFAMILIAR_FAILED: 'GET_GRUPOFAMILIAR_FAILED',

  GET_ALLGRUPOFAMILIAR_START: 'GET_ALLGRUPOFAMILIAR_START',
  GET_ALLGRUPOFAMILIAR_SUCCESS: 'GET_ALLGRUPOFAMILIAR_SUCCESS',
  GET_ALLGRUPOFAMILIAR_FAILED: 'GET_ALLGRUPOFAMILIAR_FAILED',

  GET_GRUPOFAMILIARBYEJECUTIVO_START: 'GET_GRUPOFAMILIARBYEJECUTIVO_START',
  GET_GRUPOFAMILIARBYEJECUTIVO_SUCCESS: 'GET_GRUPOFAMILIARBYEJECUTIVO_SUCCESS',
  GET_GRUPOFAMILIARBYEJECUTIVO_FAILED: 'GET_GRUPOFAMILIARBYEJECUTIVO_FAILED',

  POST_GRUPOFAMILIAR_START: 'POST_GRUPOFAMILIAR_START',
  POST_GRUPOFAMILIAR_SUCCESS: 'POST_GRUPOFAMILIAR_SUCCESS',
  POST_GRUPOFAMILIAR_FAILED: 'POST_GRUPOFAMILIAR_FAILED',

  UPDATE_GRUPOFAMILIAR_START: 'UPDATE_GRUPOFAMILIAR_START',
  UPDATE_GRUPOFAMILIAR_SUCCESS: 'UPDATE_GRUPOFAMILIAR_SUCCESS',
  UPDATE_GRUPOFAMILIAR_FAILED: 'UPDATE_GRUPOFAMILIAR_FAILED',

  DELETE_GRUPOFAMILIAR_START: 'DELETE_GRUPOFAMILIAR_START',
  DELETE_GRUPOFAMILIAR_SUCCESS: 'DELETE_GRUPOFAMILIAR_SUCCESS',
  DELETE_GRUPOFAMILIAR_FAILED: 'DELETE_GRUPOFAMILIAR_FAILED',

  UPDATE_ESTADOFAMILIAR_START: 'UPDATE_ESTADOFAMILIAR_START',
  UPDATE_ESTADOFAMILIAR_SUCCESS: 'UPDATE_ESTADOFAMILIAR_SUCCESS',
  UPDATE_ESTADOFAMILIAR_FAILED: 'UPDATE_ESTADOFAMILIAR_FAILED',

  GET_LUGARES_START: 'GET_LUGARES_START',
  GET_LUGARES_SUCCESS: 'GET_LUGARES_SUCCESS',
  GET_LUGARES_FAILED: 'GET_LUGARES_FAILED',

  GET_ALLLUGARES_START: 'GET_ALLLUGARES_START',
  GET_ALLLUGARES_SUCCESS: 'GET_ALLLUGARES_SUCCESS',
  GET_ALLLUGARES_FAILED: 'GET_ALLLUGARES_FAILED',

  POST_LUGARES_START: 'POST_LUGARES_START',
  POST_LUGARES_SUCCESS: 'POST_LUGARES_SUCCESS',
  POST_LUGARES_FAILED: 'POST_LUGARES_FAILED',

  DELETE_LUGARES_START: 'DELETE_LUGARES_START',
  DELETE_LUGARES_SUCCESS: 'DELETE_LUGARES_SUCCESS',
  DELETE_LUGARES_FAILED: 'DELETE_LUGARES_FAILED',

  UPDATE_LUGARES_START: 'UPDATE_LUGARES_START',
  UPDATE_LUGARES_SUCCESS: 'UPDATE_LUGARES_SUCCESS',
  UPDATE_LUGARES_FAILED: 'UPDATE_LUGARES_FAILED',

  UPDATE_ESTADOLUGAR_START: 'UPDATE_ESTADOLUGAR_START',
  UPDATE_ESTADOLUGAR_SUCCESS: 'UPDATE_ESTADOLUGAR_SUCCESS',
  UPDATE_ESTADOLUGAR_FAILED: 'UPDATE_ESTADOLUGAR_FAILED',

  GET_PROTECTOR_START: 'GET_PROTECTOR_START',
  GET_PROTECTOR_SUCCESS: 'GET_PROTECTOR_SUCCESS',
  GET_PROTECTOR_FAILED: 'GET_PROTECTOR_FAILED',

  GET_ALLPROTECTOR_START: 'GET_ALLPROTECTOR_START',
  GET_ALLPROTECTOR_SUCCESS: 'GET_ALLPROTECTOR_SUCCESS',
  GET_ALLPROTECTOR_FAILED: 'GET_ALLPROTECTOR_FAILED',

  DELETE_PROTECTOR_START: 'DELETE_PROTECTOR_START',
  DELETE_PROTECTOR_SUCCESS: 'DELETE_PROTECTOR_SUCCESS',
  DELETE_PROTECTOR_FAILED: 'DELETE_PROTECTOR_FAILED',

  UPDATE_PROTECTOR_START: 'UPDATE_PROTECTOR_START',
  UPDATE_PROTECTOR_SUCCESS: 'UPDATE_PROTECTOR_SUCCESS',
  UPDATE_PROTECTOR_FAILED: 'UPDATE_PROTECTOR_FAILED',

  POST_PROTECTOR_START: 'POST_PROTECTOR_START',
  POST_PROTECTOR_SUCCESS: 'POST_PROTECTOR_SUCCESS',
  POST_PROTECTOR_FAILED: 'POST_PROTECTOR_FAILED',

  UPDATE_ESTADOPROTECTOR_START: 'UPDATE_ESTADOPROTECTOR_START',
  UPDATE_ESTADOPROTECTOR_SUCCESS: 'UPDATE_ESTADOPROTECTOR_SUCCESS',
  UPDATE_ESTADOPROTECTOR_FAILED: 'UPDATE_ESTADOPROTECTOR_FAILED',

  GET_VEHICULOEJECUTIVO_START: 'GET_VEHICULOEJECUTIVO_START',
  GET_VEHICULOEJECUTIVO_SUCCESS: 'GET_VEHICULOEJECUTIVO_SUCCESS',
  GET_VEHICULOEJECUTIVO_FAILED: 'GET_VEHICULOEJECUTIVO_FAILED',

  GET_ALLVEHICULOEJECUTIVO_START: 'GET_ALLVEHICULOEJECUTIVO_START',
  GET_ALLVEHICULOEJECUTIVO_SUCCESS: 'GET_ALLVEHICULOEJECUTIVO_SUCCESS',
  GET_ALLVEHICULOEJECUTIVO_FAILED: 'GET_ALLVEHICULOEJECUTIVO_FAILED',

  POST_VEHICLE_EJECUTIVO_START: 'POST_VEHICLE_EJECUTIVO_START',
  POST_VEHICLE_EJECUTIVO_SUCCESS: 'POST_VEHICLE_EJECUTIVO_SUCCESS',
  POST_VEHICLE_EJECUTIVO_FAILED: 'POST_VEHICLE_EJECUTIVO_FAILED',

  DELETE_VEHICLE_EJECUTIVO_START: 'DELETE_VEHICLE_EJECUTIVO_START',
  DELETE_VEHICLE_EJECUTIVO_SUCCESS: 'DELETE_VEHICLE_EJECUTIVO_SUCCESS',
  DELETE_VEHICLE_EJECUTIVO_FAILED: 'DELETE_VEHICLE_EJECUTIVO_FAILED',

  UPDATE_VEHICLE_EJECUTIVO_START: 'UPDATE_VEHICLE_EJECUTIVO_START',
  UPDATE_VEHICLE_EJECUTIVO_SUCCESS: 'UPDATE_VEHICLE_EJECUTIVO_SUCCESS',
  UPDATE_VEHICLE_EJECUTIVO_FAILED: 'UPDATE_VEHICLE_EJECUTIVO_FAILED',

  UPDATE_ESTADO_VEHICULOEJECUTIVO_START:
    'UPDATE_ESTADO_VEHICULOEJECUTIVO_START',
  UPDATE_ESTADO_VEHICULOEJECUTIVO_SUCCESS:
    'UPDATE_ESTADO_VEHICULOEJECUTIVO_SUCCESS',
  UPDATE_ESTADO_VEHICULOEJECUTIVO_FAILED:
    'UPDATE_ESTADO_VEHICULOEJECUTIVO_FAILED',

  GET_VEHICULOEPROTECTOR_START: 'GET_VEHICULOEPROTECTOR_START',
  GET_VEHICULOEPROTECTOR_SUCCESS: 'GET_VEHICULOEPROTECTOR_SUCCESS',
  GET_VEHICULOEPROTECTOR_FAILED: 'GET_VEHICULOEPROTECTOR_FAILED',

  GET_ALLVEHICULOEPROTECTOR_START: 'GET_ALLVEHICULOEPROTECTOR_START',
  GET_ALLVEHICULOEPROTECTOR_SUCCESS: 'GET_ALLVEHICULOEPROTECTOR_SUCCESS',
  GET_ALLVEHICULOEPROTECTOR_FAILED: 'GET_ALLVEHICULOEPROTECTOR_FAILED',

  POST_VEHICLE_PROTECTOR_START: 'POST_VEHICLE_PROTECTOR_START',
  POST_VEHICLE_PROTECTOR_SUCCESS: 'POST_VEHICLE_PROTECTOR_SUCCESS',
  POST_VEHICLE_PROTECTOR_FAILED: 'POST_VEHICLE_PROTECTOR_FAILED',

  DELETE_VEHICLE_PROTECTOR_START: 'DELETE_VEHICLE_PROTECTOR_START',
  DELETE_VEHICLE_PROTECTOR_SUCCESS: 'DELETE_VEHICLE_PROTECTOR_SUCCESS',
  DELETE_VEHICLE_PROTECTOR_FAILED: 'DELETE_VEHICLE_PROTECTOR_FAILED',

  UPDATE_VEHICLE_PROTECTOR_START: 'UPDATE_VEHICLE_PROTECTOR_START',
  UPDATE_VEHICLE_PROTECTOR_SUCCESS: 'UPDATE_VEHICLE_PROTECTOR_SUCCESS',
  UPDATE_VEHICLE_PROTECTOR_FAILED: 'UPDATE_VEHICLE_PROTECTOR_FAILED',

  UPDATE_ESTADO_VEHICULOPROTECTOR_START:
    'UPDATE_ESTADO_VEHICULOPROTECTOR_START',
  UPDATE_ESTADO_VEHICULOPROTECTOR_SUCCESS:
    'UPDATE_ESTADO_VEHICULOPROTECTOR_SUCCESS',
  UPDATE_ESTADO_VEHICULOPROTECTOR_FAILED:
    'UPDATE_ESTADO_VEHICULOPROTECTOR_FAILED',

  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',

  GET_CONSIGNASCCTV_START: 'GET_CONSIGNASCCTV_START',
  GET_CONSIGNASCCTV_SUCCESS: 'GET_CONSIGNASCCTV_SUCCESS',
  GET_CONSIGNASCCTV_FAILED: 'GET_CONSIGNASCCTV_FAILED',

  GET_CONSIGNASTRS_START: 'GET_CONSIGNASTRS_START',
  GET_CONSIGNASTRS_SUCCESS: 'GET_CONSIGNASTRS_SUCCESS',
  GET_CONSIGNASTRS_FAILED: 'GET_CONSIGNASTRS_FAILED',

  GET_CONSIGNASGRAFICA_START: 'GET_CONSIGNASGRAFICA_START',
  GET_CONSIGNASGRAFICA_SUCCESS: 'GET_CONSIGNASGRAFICA_SUCCESS',
  GET_CONSIGNASGRAFICA_FAILED: 'GET_CONSIGNASGRAFICA_FAILED',

  GET_CONSIGNACERRARCCTV_START: 'GET_CONSIGNACERRARCCTV_START',
  CONSIGNACERRARCCTV_SUCCESS: 'GET_CONSIGNACERRARCCTV_SUCCESS',
  CONSIGNACERRARCCTV_FAILED: 'GET_CONSIGNACERRARCCTV_FAILED',

  GET_CONSIGNACERRARCTRS_START: 'GET_CONSIGNACERRARCTRS_START',
  CONSIGNACERRARTRS_SUCCESS: 'GET_CONSIGNACERRARTRS_SUCCESS',
  CONSIGNACERRARTRS_FAILED: 'GET_CONSIGNACERRARTRS_FAILED',

  GET_INFORMETRS_START: 'GET_INFORMETRS_START',
  GET_INFORMETRS_SUCCESS: 'GET_INFORMETRS_SUCCESS',
  GET_INFORMETRS_FAILED: 'GET_INFORMETRS_FAILED',
}
