export const types = {
    LOGIN_START:'LOGIN_START',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',


    REGISTER_START:'REGISTER_START',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAILED:'REGISTER_FAILED',

    GET_EJECUTIVO_START:'GET_EJECUTIVO_START',
    GET_EJECUTIVO_SUCCESS:'GET_EJECUTIVO_SUCCESS',
    GET_EJECUTIVO_FAILED:'GET_EJECUTIVO_FAILED',

    POST_EJECUTIVO_START:'POST_EJECUTIVO_START',
    POST_EJECUTIVO_SUCCESS:'POST_EJECUTIVO_SUCCESS',
    POST_EJECUTIVO_FAILED:'POST_EJECUTIVO_FAILED',

    DELETE_EJECUTIVO_START:'DELETE_EJECUTIVO_START',
    DELETE_EJECUTIVO_SUCCESS:'DELETE_EJECUTIVO_SUCCESS',
    DELETE_EJECUTIVO_FAILED:'DELETE_EJECUTIVO_FAILED',

    UPDATE_EJECUTIVO_START:'UPDATE_EJECUTIVO_START',
    UPDATE_EJECUTIVO_SUCCESS:'UPDATE_EJECUTIVO_SUCCESS',
    UPDATE_EJECUTIVO_FAILED:'UPDATE_EJECUTIVO_FAILED',

    GET_LUGARES_START:'GET_LUGARES_START',
    GET_LUGARES_SUCCESS:'GET_LUGARES_SUCCESS',
    GET_LUGARES_FAILED:'GET_LUGARES_FAILED',

    POST_LUGARES_START:'POST_LUGARES_START',
    POST_LUGARES_SUCCESS:'POST_LUGARES_SUCCESS',
    POST_LUGARES_FAILED:'POST_LUGARES_FAILED',

    DELETE_LUGARES_START:'DELETE_LUGARES_START',
    DELETE_LUGARES_SUCCESS:'DELETE_LUGARES_SUCCESS',
    DELETE_LUGARES_FAILED:'DELETE_LUGARES_FAILED',

    UPDATE_LUGARES_START:'UPDATE_LUGARES_START',
    UPDATE_LUGARES_SUCCESS:'UPDATE_LUGARES_SUCCESS',
    UPDATE_LUGARES_FAILED:'UPDATE_LUGARES_FAILED',

    DELETE_PROTECTOR_START:'DELETE_PROTECTOR_START',
    DELETE_PROTECTOR_SUCCESS:'DELETE_PROTECTOR_SUCCESS',
    DELETE_PROTECTOR_FAILED:'DELETE_PROTECTOR_FAILED',
    
    UPDATE_PROTECTOR_START:'UPDATE_PROTECTOR_START',
    UPDATE_PROTECTOR_SUCCESS:'UPDATE_PROTECTOR_SUCCESS',
    UPDATE_PROTECTOR_FAILED:'UPDATE_PROTECTOR_FAILED',

    POST_PROTECTOR_START:'POST_PROTECTOR_START',
    POST_PROTECTOR_SUCCESS:'POST_PROTECTOR_SUCCESS',
    POST_PROTECTOR_FAILED:'POST_PROTECTOR_FAILED',


    POST_VEHICLE_EJECUTIVO_START:'POST_VEHICLE_EJECUTIVO_START',
    POST_VEHICLE_EJECUTIVO_SUCCESS:'POST_VEHICLE_EJECUTIVO_SUCCESS',
    POST_VEHICLE_EJECUTIVO_FAILED:'POST_VEHICLE_EJECUTIVO_FAILED',

    DELETE_VEHICLE_EJECUTIVO_START:'DELETE_VEHICLE_EJECUTIVO_START',
    DELETE_VEHICLE_EJECUTIVO_SUCCESS:'DELETE_VEHICLE_EJECUTIVO_SUCCESS',
    DELETE_VEHICLE_EJECUTIVO_FAILED:'DELETE_VEHICLE_EJECUTIVO_FAILED',
    
    UPDATE_VEHICLE_EJECUTIVO_START:'UPDATE_VEHICLE_EJECUTIVO_START',
    UPDATE_VEHICLE_EJECUTIVO_SUCCESS:'UPDATE_VEHICLE_EJECUTIVO_SUCCESS',
    UPDATE_VEHICLE_EJECUTIVO_FAILED:'UPDATE_VEHICLE_EJECUTIVO_FAILED',


    POST_VEHICLE_PROTECTOR_START:'POST_VEHICLE_PROTECTOR_START',
    POST_VEHICLE_PROTECTOR_SUCCESS:'POST_VEHICLE_PROTECTOR_SUCCESS',
    POST_VEHICLE_PROTECTOR_FAILED:'POST_VEHICLE_PROTECTOR_FAILED',

    DELETE_VEHICLE_PROTECTOR_START:'DELETE_VEHICLE_PROTECTOR_START',
    DELETE_VEHICLE_PROTECTOR_SUCCESS:'DELETE_VEHICLE_PROTECTOR_SUCCESS',
    DELETE_VEHICLE_PROTECTOR_FAILED:'DELETE_VEHICLE_PROTECTOR_FAILED',
    
    UPDATE_VEHICLE_PROTECTOR_START:'UPDATE_VEHICLE_PROTECTOR_START',
    UPDATE_VEHICLE_PROTECTOR_SUCCESS:'UPDATE_VEHICLE_PROTECTOR_SUCCESS',
    UPDATE_VEHICLE_PROTECTOR_FAILED:'UPDATE_VEHICLE_PROTECTOR_FAILED',

    SHOW_TOAST:'SHOW_TOAST',
    HIDE_TOAST:'HIDE_TOAST',
}