export {default as EjectivosTable} from './EjectivosTable'
export {default as FamilyTable} from './FamilyTable'
export {default as VehiculosEjecutivoTable} from './VehiculosEjecutivoTable'
export {default as ProtectoresTable} from './ProtectoresTable'
export {default as VehiculosProtectTable} from './VehiculosProtectTable'
export {default as LugaresTable} from './LugaresTable'